[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 10000
verbosity = 1
solc_version = '0.8.18'

[fmt]
line_length = 80
number_underscore = "thousands"
wrap_comments = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }